name: Deploy to Google Cloud VM

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'  # Your service account key stored in GitHub Secrets

      # Step 3: Set up Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}  # Your Google Cloud project ID
          install_components: 'beta'  # Optional: Install additional components if needed

      # Step 4: Set up SSH key for connecting to the VM
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh  # Create the .ssh directory if it doesn't exist
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/google_compute_engine  # Add the private key from GitHub Secrets
          chmod 600 ~/.ssh/google_compute_engine  # Set the correct permissions for the private key
          # Generate the public key if it doesn't exist
          if [ ! -f ~/.ssh/google_compute_engine.pub ]; then
            ssh-keygen -y -f ~/.ssh/google_compute_engine > ~/.ssh/google_compute_engine.pub
          fi
          ssh-keyscan -H ${{ secrets.GCP_VM_IP }} >> ~/.ssh/known_hosts  # Add the VM's IP to known hosts to avoid SSH prompts

      # Step 5: Debug Information
      - name: Debug Information
        run: |
          echo "SSH User is set."
          echo "VM IP is set."

      # Step 6: Test SSH Connection
      - name: Test SSH Connection
        run: |
          gcloud compute ssh lekappdev@$34.176.181.231 --zone southamerica-west1-b --command "ls /var/www/html/app.lekapp.cl"

      # Step 7: Deploy to the VM
      - name: Deploy to VM
        run: |
          # Copy files to the VM
          gcloud compute scp --recurse . lekappdev@34.176.181.231:/var/www/html/app.lekapp.cl --zone southamerica-west1-b
