name: Deploy to Google Cloud VM

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'  # Your service account key

      # Step 3: Set up Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}  # Your Google Cloud project ID

      # Step 4: Set up SSH key for connecting to the VM
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh  # Create the .ssh directory if it doesn't exist
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/google_compute_engine  # Add the private key from GitHub Secrets
          chmod 600 ~/.ssh/google_compute_engine  # Set the correct permissions for the private key
          # Ensure the public key is not generated or overwritten
          if [ ! -f ~/.ssh/google_compute_engine.pub ]; then
            echo "Public key not found. Please ensure the public key is set in the VM instance metadata."
            exit 1
          fi
          ssh-keyscan -H ${{ secrets.GCP_VM_IP }} >> ~/.ssh/known_hosts  # Add the VM's IP to known hosts to avoid SSH prompts

      # Step 5: Copy files to the VM
      - name: Copy files to the VM
        run: |
          gcloud compute scp --recurse . ${{ secrets.GCP_SSH_USER }}@${{ secrets.GCP_VM_IP }}:/var/www/html/app.lekapp.cl --zone southamerica-west1-b

      # Step 6: (Optional) Run commands on the VM after copying files
      # Uncomment and customize the following lines if you want to run commands on the VM
      # - name: Run commands on the VM
      #   run: |
      #     gcloud compute ssh ${{ secrets.GCP_SSH_USER }}@${{ secrets.GCP_VM_IP }} --zone southamerica-west1-b --command "cd /var/www/html/app.lekapp.cl && npm install && npm start"
