name: Deploy to Google Cloud VM

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'  # Your service account key

      # Step 3: Deploy to Server
      - name: Deploy to Server
        run: |
          ssh -i ~/.ssh/googlecloud ${{ secrets.GCP_SSH_USER }}@${{ secrets.GCP_VM_IP }} "
            if [ ! -d /var/www/html/app.lekapp.cl/.git ]; then
              git clone https://github.com/lekapp/lekapp-backoffice-v2.git /var/www/html/app.lekapp.cl;  # Use HTTPS URL
            else
              cd /var/www/html/app.lekapp.cl
              git remote set-url origin https://github.com/lekapp/lekapp-backoffice-v2.git;  # Use HTTPS URL
              git pull origin main;
            fi
          "
